# Generated by Django 3.1.3 on 2020-12-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name and last name')),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='images/members')),
            ],
            options={
                'verbose_name_plural': 'Members Profile',
                'ordering': ['-id'],
            },
        ),
    ]
