# Generated by Django 3.1.3 on 2020-12-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersprofile',
            name='img',
            field=models.ImageField(upload_to='static/img/upload/members'),
        ),
    ]
