# Generated by Django 3.1.3 on 2020-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20201212_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersprofile',
            name='bio',
            field=models.TextField(),
        ),
    ]
