# Generated by Django 3.1.3 on 2020-12-05 12:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_date', models.DateField(verbose_name='begin of the  activity')),
                ('ed_date', models.DateField(verbose_name='end of the  activity')),
                ('text', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
