# Generated by Django 3.1.3 on 2020-12-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201205_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Activity'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name_plural': 'Articles'},
        ),
    ]
