# Generated by Django 3.1.3 on 2020-12-05 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201205_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Articles'},
        ),
    ]
